/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf 
Author: ChristyHsu (https://sketchfab.com/ida61xq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dining-room-kichen-baked-4831c2ce6a0044d9bee9eacefcc0f2bd
Title: Dining room | Kichen baked
*/

import React, { useMemo, useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('public/models/dinning_room/scene.gltf');
const floorRef=useRef();

   const texture=useTexture('public/models/dinning_room/textures/laminate3.png')
// floorRef.material.map=texture;
// floorRef.material.needsUpdate=true;
  



  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[388.469, 117.552, -211.434]} rotation={[-Math.PI / 2, 0.148, 0]} scale={[2.712, 31.279, 31.279]}>
          <mesh geometry={nodes.painting_Material010_0.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.painting_Material011_0.geometry} material={materials['Material.011']} />
        </group>
        <group position={[366.217, 115.97, -143.771]} rotation={[-Math.PI / 2, 0, 0]} scale={3.789}>
          <mesh geometry={nodes.candle_Material013_0.geometry} material={materials['Material.013']} />
          <mesh geometry={nodes.candle_Material008_0.geometry} material={materials['Material.008']} />
          <mesh geometry={nodes.candle_Material007_0.geometry} material={materials['Material.007']} />
        </group>
        <group position={[85.821, 88.279, 64.486]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.flower_leaf2_0.geometry} material={materials.leaf2} />
          <mesh geometry={nodes.flower_leaf1_0.geometry} material={materials.leaf1} />
        </group>
        <group position={[188.831, 243.457, -26.58]} rotation={[-Math.PI / 2, 0, 0]} scale={[2.688, 2.688, 23.024]}>
          <mesh geometry={nodes.lighting_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.lighting_Material003_0.geometry} material={materials['Material.003']} />
          <mesh geometry={nodes.lighting_Material014_0.geometry} material={materials['Material.014']} />
        </group>
        <group position={[81.651, 59.793, -127.726]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[25.257, 25.257, 2.667]}>
          <mesh geometry={nodes.seat_Leather_0.geometry} material={materials.Leather} />
          <mesh geometry={nodes.seat_Material5_0.geometry} material={materials.Material5} />
        </group>
        <mesh geometry={nodes.house_Material009_0.geometry} material={materials['Material.009']} position={[0, 151.309, -0.282]} rotation={[-Math.PI / 2, 0, 0]} scale={[396.176, 396.176, 150]} />
        <mesh geometry={nodes.cabinet_Material015_0.geometry} material={materials['Material.015']} position={[367.527, 300.186, 45.941]} rotation={[-Math.PI / 2, 0, 0]} scale={[34.407, 249.171, 3.605]} />
        <mesh geometry={nodes.window_Material016_0.geometry} material={materials['Material.016']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.table_Material5001_0.geometry} material={materials['Material5.001']} position={[83.1, 65.739, 24.667]} rotation={[-Math.PI / 2, 0, 0]} scale={[80.747, 80.747, 10.763]} />
       
        <mesh ref={floorRef} geometry={nodes.floor_floor_0.geometry}  material={materials.floor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.jar4_Material017_0.geometry} material={materials['Material.017']} position={[377.036, 94.34, 219.292]} rotation={[-Math.PI / 2, 0, 0]} scale={7.771} />
        <mesh geometry={nodes.jar3_Material002_0.geometry} material={materials['Material.002']} position={[383.419, 94.983, 239.01]} rotation={[-Math.PI / 2, 0, 0]} scale={8.337} />
        <mesh geometry={nodes.vase_grey001_0.geometry} material={materials['grey.001']} position={[85.258, 86.332, 64.115]} rotation={[-Math.PI / 2, 0, 0]} scale={8.337} />
        <mesh geometry={nodes.faucet_Material006_0.geometry} material={materials['Material.006']} position={[392.071, 95.046, 141.652]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.204, 0.204, 1.555]} />
        <mesh geometry={nodes.bowl_grey_0.geometry} material={materials.grey} position={[372.827, 99.081, 270.913]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.524, 16.524, 12.674]} />
        <mesh geometry={nodes.IKEA_seat_wood__0.geometry} material={materials.wood} position={[363.595, 31.995, -331.439]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[17.536, 15.514, 15.514]} />
        <mesh geometry={nodes.carpet_Carpet__0.geometry} material={materials.Carpet} position={[81.578, 2.411, 26.536]} rotation={[-Math.PI / 2, 0, 0]} scale={[190.768, 245.015, 0.524]} />
        <mesh geometry={nodes.chopping_board1_Material1_0.geometry} material={materials.Material1} position={[388.318, 97.913, 187.245]} rotation={[-1.593, -1.28, -0.023]} scale={[1.332, 1.546, 1.332]} />
        <mesh geometry={nodes.chopping_board2_Material2_0.geometry} material={materials.Material2} position={[391.595, 98.773, 194.446]} rotation={[-1.6, -1.347, -0.03]} scale={[1.399, 1.586, 1.399]} />
        <mesh geometry={nodes.jar1_Material3_0.geometry} material={materials.Material3} position={[375.22, 92.792, -108.769]} rotation={[-Math.PI / 2, 0, -1.875]} scale={0.898} />
        <mesh geometry={nodes.jar2_Material4_0.geometry} material={materials.Material4} position={[372.586, 97.235, -121.78]} rotation={[-Math.PI / 2, 0, -1.247]} scale={0.824} />
      </group>
    </group>
  )
}

useGLTF.preload('public/models/dinning_room/scene.gltf')
